BEGIN;

ALTER TABLE package RENAME COLUMN volume TO height ;
ALTER TABLE package ADD width FLOAT DEFAULT 1;
ALTER TABLE package ADD depth FLOAT DEFAULT 1;

ALTER TABLE package ALTER COLUMN width DROP default;
ALTER TABLE package ALTER COLUMN depth DROP default;

COMMIT;